// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZD3TH-TJFzWIqIvA4RctT4yy-pxJg8NY',
    appId: '1:1007580337827:web:3b809d43660936fadf5116',
    messagingSenderId: '1007580337827',
    projectId: 'chris-couture',
    authDomain: 'chris-couture.firebaseapp.com',
    storageBucket: 'chris-couture.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7PbZj5838egFhwKyK4EtcP-3RHDH595w',
    appId: '1:1007580337827:android:522e66069c6726b5df5116',
    messagingSenderId: '1007580337827',
    projectId: 'chris-couture',
    storageBucket: 'chris-couture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnprxxahWplu6nmrwWXK3nz8ON5C-2vjo',
    appId: '1:1007580337827:ios:d0dc4b5be7097c84df5116',
    messagingSenderId: '1007580337827',
    projectId: 'chris-couture',
    storageBucket: 'chris-couture.firebasestorage.app',
    iosBundleId: 'com.stylish.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnprxxahWplu6nmrwWXK3nz8ON5C-2vjo',
    appId: '1:1007580337827:ios:d0dc4b5be7097c84df5116',
    messagingSenderId: '1007580337827',
    projectId: 'chris-couture',
    storageBucket: 'chris-couture.firebasestorage.app',
    iosBundleId: 'com.stylish.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZD3TH-TJFzWIqIvA4RctT4yy-pxJg8NY',
    appId: '1:1007580337827:web:ef35610d837d3020df5116',
    messagingSenderId: '1007580337827',
    projectId: 'chris-couture',
    authDomain: 'chris-couture.firebaseapp.com',
    storageBucket: 'chris-couture.firebasestorage.app',
  );
}
